version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    restart: no
    ports:
      - "5433:5432"
    environment:
      - 'POSTGRES_DB=uvbot'
      - 'POSTGRES_PASSWORD=UvBotPassword6969!'
      - 'POSTGRES_USER=postgres'
