services:
  postgres:
    image: 'postgres:16'
    restart: no
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
