version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    restart: no
    environment:
      - 'POSTGRES_DB=uvbot'
      - 'POSTGRES_PASSWORD=UvBotPassword6969!'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
