services:
  postgres:
    image: 'postgres:16'
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB:-uvbot}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-local}'
      - 'POSTGRES_USER=${POSTGRES_USER:-postgres}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
    image: ghcr.io/konstantin-matrokhin/uv-index-bot:latest
    container_name: uvindexbot-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
