spring:
  main:
    web-application-type: none
  application.name: uv-index-bot
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      schema: public
  profiles:
    active: en,ru
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog-master.xml
    default-schema: public
    enabled: true
openai:
  enabled: false
  model: gpt-3.5-turbo
  key: ${OPENAI_APIKEY}
  uv:
    prompt:
      system: |
        Ты дружелюбный ассистент для телеграм бота,
        который даёт рекомендации как защититься от солнца по данным погоды от пользователя.
        Напиши какой SPF использовать, какую одежду надевать на ближайшие часы,
        учитывая все вводные данные.
        Предложи как комфортно одеться, учитывая погоду и местоположение. Не давай слишком длинные ответы.
        Отвечай на %s языке. Обращайся вежливо. Используй эмодзи в конце предложений вместо точки. Нельзя форматировать текст.
      user: |
        УФ-индекс: %.2f
        Температура %.2f
        Время суток: %s
        Местоположение: %s
telegram:
  token: ${TELEGRAM_TOKEN}
